export const COLORS = {
  light: {
    primary: '#6C3CE1',
    primaryDark: '#4A1DB5',
    primaryLight: '#8B5CF6',
    secondary: '#00D4AA',
    accent: '#FF6B6B',
    background: '#F0F2F8',
    surface: '#FFFFFF',
    surfaceAlt: '#F8F9FC',
    text: '#1A1D2E',
    textSecondary: '#6B7280',
    border: '#E5E7EB',
    overlay: 'rgba(255,255,255,0.2)',
    gradient: ['#6C3CE1', '#4A1DB5'] as [string, string],
    gradientSecondary: ['#8B5CF6', '#6C3CE1'] as [string, string],
    cardShadow: {
      shadowColor: '#6C3CE1',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 4,
    },
  },
  dark: {
    primary: '#8B5CF6',
    primaryDark: '#6C3CE1',
    primaryLight: '#A78BFA',
    secondary: '#00D4AA',
    accent: '#FF6B6B',
    background: '#0F0F1A',
    surface: '#1A1A2E',
    surfaceAlt: '#16213E',
    text: '#F1F5F9',
    textSecondary: '#94A3B8',
    border: '#2D2D44',
    overlay: 'rgba(0,0,0,0.4)',
    gradient: ['#1A1A2E', '#0F0F1A'] as [string, string],
    gradientSecondary: ['#8B5CF6', '#6C3CE1'] as [string, string],
    cardShadow: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 6,
    },
  },
  danger: '#EF4444',
  success: '#10B981',
  warning: '#F59E0B',
  info: '#3B82F6',
};

export const GUNLER = ["Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma", "Cumartesi", "Pazar"];
export const SIZES = { radius: 20, padding: 20, fontTitle: 24, fontSub: 14 };